version: '3.8'
services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8080"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./target:/app/target
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/product
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: product
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data: