spring:
  application:
    name: product-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/produtos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      pool-name: product-db-pool
      max-lifetime: 600000
      connection-timeout: 60000
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true